name: Lint Code Base

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - development

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          LOG_LEVEL: WARN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linter
          JAVA_FILE_NAME: google-java-style.xml